name: bali_weather_app
description: "Simple weather forecast app using OpenWeather API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Font & ikon iOS-style
  cupertino_icons: ^1.0.8

  # HTTP client untuk call OpenWeather API
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
